name: Build APK

on:
  push:
    branches: [ "**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Android SDK
        uses: android-actions/setup-android@v4
        with:
          log-accepted-android-sdk-licenses: false
          packages: 'platforms;android-37 build-tools;37.0.0 platform-tools'

      - name: Install NDK
        run: |
          echo "y" | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager \
            --channel=0 \
            --install "ndk;29.0.14206865"
          echo "NDK_HOME=$ANDROID_HOME/ndk/29.0.14206865" >> $GITHUB_ENV
          sed -i '10i\
        \
            ndkVersion = "29.0.14206865"' ${{ github.workspace }}/V2rayNG/app/build.gradle.kts

      - name: Build libhevtun (native tunnel library)
        run: bash compile-hevtun.sh

      - name: Copy libhevtun into app module
        run: cp -r ${{ github.workspace }}/libs ${{ github.workspace }}/V2rayNG/app

      - name: Download libv2ray.aar (Xray core)
        uses: robinraju/release-downloader@v1.13
        with:
          repository: '2dust/AndroidLibXrayLite'
          tag: 'v26.5.9'
          fileName: 'libv2ray.aar'
          out-file-path: V2rayNG/app/libs/

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build debug APK
        run: |
          cd ${{ github.workspace }}/V2rayNG
          echo "sdk.dir=${ANDROID_HOME}" > local.properties
          chmod 755 gradlew
          ./gradlew assembleDebug --stacktrace

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        if: success()
        with:
          name: m-debug-apk
          path: V2rayNG/app/build/outputs/apk/**/*.apk

